webapps/django/steamy/debian/urls.py
# -*- coding: utf-8 -*-
#
# Nacho Barrientos Arias <nacho@debian.org>
#
# License: MIT

from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('debian.views',
    (r'^$', 'index'),
    (r'^sparql/$', 'sparql'),
    (r'^results/$', 'results'),
    (r'^results/news/$', 'allnews'),
    (r'^news/(?P<source>[^/ ]+)/$', 'news'),
    (r'^seealso/(?P<source>[^/ ]+)/$', 'seealso'),
    (r'^binaries/(?P<source>[^/ ]+)/(?P<version>[^/ ]+)/$', 'source_detail'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

webapps/django/steamy/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^debian/', include('steamy.debian.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/(.*)', admin.site.root),
)

webapps/django/steamy/debian/forms.py
# -*- coding: utf-8 -*-
#
# Nacho Barrientos Arias <nacho@debian.org>
#
# License: MIT

import re

from django.forms import widgets
from django import forms
from django.shortcuts import render_to_response
from django.utils.safestring import mark_safe

from debian.config import SPARQL_PREFIXES, RES_BASEURI, ONT_URI 
from debian.config import DEFAULT_QUERY
from debian.services import SPARQLQueryBuilder, SPARQLQueryProcessor


# Thanks: http://www.djangosnippets.org/snippets/316/
class HiddenBaseForm(forms.BaseForm):
    def as_hidden(self):
        """
        Returns this form rendered entirely as hidden fields.
        """
        return mark_safe(u'\n'.join(forms.forms.BoundField(self, field, name).as_hidden() \
                                    for name, field in self.fields.items()))
    as_hidden.needs_autoescape = True


DIST_OPTS = (
    ('ANY', 'any'),
    (RES_BASEURI+'/distribution/hamm', 'Hamm'),
    (RES_BASEURI+'/distribution/slink', 'Slink'),
    (RES_BASEURI+'/distribution/potato', 'Potato'),
    (RES_BASEURI+'/distribution/woody', 'Woody'),
    (RES_BASEURI+'/distribution/sarge', 'Sarge'),
    (RES_BASEURI+'/distribution/etch', 'Etch'),
    (RES_BASEURI+'/distribution/lenny', 'Lenny'),
)

PRIORITY_OPTS = (
    ('ANY', 'any'),
    (ONT_URI+'required', 'required'),
    (ONT_URI+'important', 'important'),
    (ONT_URI+'standard', 'standard'),
    (ONT_URI+'optional', 'optional'),
    (ONT_URI+'extra', 'extra'),
)

AREA_OPTS = (
    ('ANY', 'any'),
    (ONT_URI+'main', 'main'),
    (ONT_URI+'non-free', 'non-free'),
    (ONT_URI+'contrib', 'contrib'),
)

SEARCHTYPE_OPTS = (
    ('SOURCE', 'Source package names'),
    ('BINARY', 'Binary package names'),
    ('BINARYEXT', 'Binary package names and descriptions'),
)

MAINT_OPTS = (
    ('ALL', 'No restriction'),
    ('TEAM', 'Team-maintained packages'),
    ('DEBIAN', 'Only maintainers with @debian.org address'),
    ('QA', 'Maintainer is Debian Quality Assurance Group'),
    ('CUSTOM', 'Custom filter (use text field below to set one)'),
)

COMAINT_OPTS = (
    ('ALL', 'No restriction'),
    ('WITH', 'With comantainers'),
    ('WITHOUT', 'Without them'),
)

VERSION_OPTS = (
    ('NATIVE', 'Native'),
    ('NMU', 'NMUed'),
    ('EPOCH', 'With epoch'),
)

VCS_OPTS = (
    ('SVN', 'Subversion'),
    ('GIT', 'Git'),
    ('CVS', 'Cvs'),
    ('HG', 'Mercurial'),
)

SORT_OPTS = (
    ('PACKAGE', 'Package name'),
    ('MAINTMAIL', 'Maintainer email'),
)


class SearchForm(forms.Form, HiddenBaseForm):
    distribution = forms.ChoiceField(widget=widgets.Select, choices=DIST_OPTS)
    area = forms.ChoiceField(widget=widgets.Select, choices=AREA_OPTS)
    searchtype = forms.ChoiceField(initial="SOURCE", label="Search in:",\
        widget=widgets.RadioSelect, choices=SEARCHTYPE_OPTS)
    filter = forms.RegexField(regex=re.compile(r"^[-a-zA-Z0-9+.]*$"),\
        max_length=30, required=False)
    exactmatch = forms.BooleanField(required=False)
    priority = forms.ChoiceField(choices=PRIORITY_OPTS)
    maintainer = forms.ChoiceField(initial="ALL",\
        widget=widgets.RadioSelect, choices=MAINT_OPTS)
    comaintainer = forms.ChoiceField(initial="ALL",\
        widget=widgets.RadioSelect, choices=COMAINT_OPTS)
    version = forms.MultipleChoiceField(\
        widget=widgets.CheckboxSelectMultiple, choices=VERSION_OPTS,\
        required=False)
    vcs = forms.MultipleChoiceField(widget=widgets.CheckboxSelectMultiple,\
        choices=VCS_OPTS, required=False)
    essential = forms.BooleanField(required=False)
    buildessential = forms.BooleanField(required=False)
    dmuploadallowed = forms.BooleanField(required=False)
    homepage = forms.BooleanField(required=False)
    sort = forms.ChoiceField(initial="PACKAGE",\
        widget=widgets.RadioSelect, choices=SORT_OPTS)
    showquery = forms.BooleanField(required=False)
    popcon = forms.BooleanField(required=False)
    section = forms.RegexField(regex=re.compile(r"^[a-zA-Z]*$"),\
        max_length=20, required=False)
    maintainerfilter = forms.RegexField(regex=re.compile(r"^[-\w@.+ ]*$", re.UNICODE),\
        max_length=40, required=False)
    tojson = forms.BooleanField(required=False)

class SPARQLForm(forms.Form):
    ns = forms.CharField(required=False, initial=SPARQL_PREFIXES, widget=widgets.Textarea())
    query = forms.CharField(initial=DEFAULT_QUERY, widget=widgets.Textarea())
    tojson_sparql = forms.BooleanField(required=False)

webapps/django/steamy/debian/views.py
# -*- coding: utf-8 -*-
#
# Nacho Barrientos Arias <nacho@debian.org>
#
# License: MIT

from django.http import HttpResponse
from django.shortcuts import render_to_response, redirect
from django.utils.encoding import smart_str
from django.utils import simplejson

from debian.forms import SPARQLForm, SearchForm
from debian.services import SPARQLQueryProcessor, SPARQLQueryBuilder
from debian.services import FeedFinder, SeeAlsoFinder, remove_duplicates
from debian.errors import SPARQLQueryProcessorError, UnexpectedSituationError
from debian.errors import SPARQLQueryBuilderError


def index(request):
    if request.method == 'GET':
        searchform = SearchForm()
        sparqlform = SPARQLForm()
        dict = {'search': searchform, 'sparql': sparqlform}
        return render_to_response('debian/search.html', dict)
    else:
        return HttpResponse("405 - Method not allowed", status=405)

def sparql(request):
    if request.method == 'POST':
        sparqlform = SPARQLForm(request.POST)
        
        if sparqlform.is_valid() is False:
            searchform = SearchForm()
            dict = {'search': searchform, 'sparql': sparqlform}
            return render_to_response('debian/search.html', dict)

        query = sparqlform.cleaned_data['ns'] + sparqlform.cleaned_data['query']
        processor = SPARQLQueryProcessor()
        try:
            processor.execute_query(smart_str(query))
        except SPARQLQueryProcessorError, e:
            return render_to_response('debian/error.html', {'reason': e})

        if sparqlform.cleaned_data['tojson_sparql'] is True:
            return HttpResponse(simplejson.dumps(processor.results), \
                mimetype="application/json")
        else:
            (variables, results) = processor.format_sparql_results()
            dict = {'variables': variables, 'results': results}
            return render_to_response('debian/results.html', dict)
    else:
        return HttpResponse("405 - Method not allowed", status=405)

def results(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)

        if searchform.is_valid() is False:
            sparqlform = SPARQLForm()
            dict = {'search': searchform, 'sparql': sparqlform}
            return render_to_response('debian/search.html', dict)
        
        data = searchform.cleaned_data
        builder = SPARQLQueryBuilder()
        try:
            query = builder.create_query_from_form(data)
        except SPARQLQueryBuilderError, e:
            return render_to_response('debian/error.html', {'reason': e})

        processor = SPARQLQueryProcessor()
        try:
            processor.execute_sanitized_query(query)
        except SPARQLQueryProcessorError, e:
            return render_to_response('debian/error.html', {'reason': e})

        if builder.wants_json():
            return HttpResponse(simplejson.dumps(processor.results), \
                mimetype="application/json")
        elif builder.wants_html():
            if builder.source_search():
                results = processor.format_source_results()
            elif builder.binary_search():
                results = processor.format_binary_results()
            else:
                raise UnexpectedSituationError()
        else:
            raise UnexpectedSituationError()

        replydata = {'results': results, 'filter': data['filter']}
        replydata['query'] = query if data['showquery'] else None
        replydata['show_popcon'] = True if data['popcon'] else False
        replydata['memory'] = searchform.as_hidden()

        if builder.source_search():
            return render_to_response('debian/source_results.html', replydata)
        elif builder.binary_search():
            return render_to_response('debian/binary_results.html', replydata)
        else:
            raise UnexpectedSituationError()
    else:
        return HttpResponse("405 - Method not allowed", status=405)

def news(request, source):
    if request.method == 'GET':
        finder = FeedFinder()
        try:
            feeds = finder.populate_feeds(source)
        except (SPARQLQueryProcessorError, SPARQLQueryBuilderError), e:
            return render_to_response('debian/error.html', {'reason': e})

        replydata = {'source': source, 'feeds': feeds}
        return render_to_response('debian/news.html', replydata)
    else:
        return HttpResponse("405 - Method not allowed", status=405)

def allnews(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)
        
        if searchform.is_valid() is False:
            return HttpResponse("400 - Bad request", status=400)

        data = searchform.cleaned_data
        builder = SPARQLQueryBuilder()
        try:
            query = builder.create_query_from_form(data)
        except SPARQLQueryBuilderError, e:
            return render_to_response('debian/error.html', {'reason': e})

        processor = SPARQLQueryProcessor()
        try:
            processor.execute_sanitized_query(query)
        except SPARQLQueryProcessorError, e:
            return render_to_response('debian/error.html', {'reason': e})

        if builder.source_search():
            results = processor.format_source_results()
        elif builder.binary_search():
            results = processor.format_binary_results()
        else:
            raise UnexpectedSituationError()

        sourcenames = [x.sourcename for x in results]
        if builder.binary_search():
            sourcenames = remove_duplicates(sourcenames, lambda x: x)

        finder = FeedFinder()
        aggregated_feeds = []
        for sourcename in sourcenames:
            aggregated_feeds.extend(finder.populate_feeds(sourcename))

        replydata = {'source': '', 'feeds': aggregated_feeds}
        return render_to_response('debian/news.html', replydata)
    else:
        return HttpResponse("405 - Method not allowed", status=405)

def source_detail(request, source, version):
    if request.method == 'GET':
        builder = SPARQLQueryBuilder()
        try:
            query = builder.create_binaries_query(source, version)
        except SPARQLQueryBuilderError, e:
            return render_to_response('debian/error.html', {'reason': e})

        processor = SPARQLQueryProcessor()
        try:
            processor.execute_query(query)
        except SPARQLQueryProcessorError, e:
            return render_to_response('debian/error.html', {'reason': e})

        results = processor.format_binary_results()
        return render_to_response('debian/binary_results.html', {'results': results})
    else:
        return HttpResponse("405 - Method not allowed", status=405)

def seealso(request, source):
    if request.method == 'GET':
        finder = SeeAlsoFinder()
        try:
            uris = finder.find(source)
        except (SPARQLQueryProcessorError, SPARQLQueryBuilderError), e:
            return render_to_response('debian/error.html', {'reason': e})

        replydata = {'source': source, 'uris': uris}
        return render_to_response('debian/seealso.html', replydata)
    else:
        return HttpResponse("405 - Method not allowed", status=405)

webapps/django/templates/debian/search/assisted-search.html
<div id="tab-search">
    <div class="ui-widget">
        <div class="ui-state-highlight ui-corner-all" style="font-size: small; margin-top: 20px; padding: 0 .7em;"> 
            <p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
                Are you a newcomer? Click help tab, there's useful information there!</p>
        </div>
    </div>

    <form action="{% url debian.views.results %}" method="post">
    <div id="accordion"> 
    <h3><a href="#">Basic search</a></h3>
    <div> <!-- Basic search -->
        <div class="form-field">
            <label for="id_filter" class="field-label">Keyword:</label>
            {{ search.filter }}
            <span class="field-comment">
                (blank is ok, although the result set will be automatically limited in size)
            </span>
            {% for error in search.filter.errors %}
                <div class="ui-widget">
                    <div class="ui-state-error ui-corner-all"
                        style="width: 40%; padding: 0 .7em; margin-bottom: .2em;"> 
                    <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
                    <strong>Error:</strong> {{ error }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="form-field">
            <label for="id_distribution" class="field-label">Distribution:</label>
            {{ search.distribution }}
            <label for="id_area" class="field-label">Area:</label>
            {{ search.area }}
        </div>
        <div class="form-field">
            <label class="field-label">Search in:</label>
            {{ search.searchtype }}
        </div>
        <div class="form-field">
            {{ search.exactmatch }}
            <label for="id_exactmatch" class="field-label">Only exact matches</label>
        </div>
    </div>

    <h3><a href="#">Filters</a></h3>
    <div> <!-- Filters -->
        <fieldset>
        <legend>Common filters</legend>
        <div class="form-field">
            <label for="id_section" class="field-label">Section:</label>
            {{ search.section }}
            <span class="field-comment">
                (e.g. games, text...)
            </span>
            {% for error in search.section.errors %}
                <div class="ui-widget">
                    <div class="ui-state-error ui-corner-all" style="padding: 0 .7em; margin-bottom: .3em;"> 
                    <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
                    <strong>Error:</strong> {{ error }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="form-field">
            <label class="field-label">Priority:</label>
            {{ search.priority }}
        </div>
        <div class="form-field">
            <label class="field-label">Version:</label>
            <span class="field-comment">
                (if no option is checked no restriction will be applied)
            </span>
            {{ search.version }}
        </div>
        <div class="form-field">
            <label class="field-label">Maintainer:</label>
            {{ search.maintainer }}
        </div>
        <div class="form-field" style="margin-left: 5%">
            {{ search.maintainerfilter }}
            <span class="field-comment">
                <span class="ui-icon ui-icon-alert" style="display: inline-block;"></span>
                Case sensitive
                (e.g. Joe, deity@debian.org)
            </span>
            {% for error in search.maintainerfilter.errors %}
                <div class="ui-widget">
                    <div class="ui-state-error ui-corner-all" style="padding: 0 .7em; margin-bottom: .3em;"> 
                    <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
                    <strong>Error:</strong> {{ error }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="form-field">
            <label class="field-label">Comaintainer:</label>
            {{ search.comaintainer }}
        </div>
        <div class="form-field">
            <label class="field-label">Maintained using:</label>
            <span class="field-comment">
                (if no option is checked no restriction will be applied)
            </span>
            {{ search.vcs }}
        </div>
        </fieldset>
        <fieldset>
        <legend>Source search filters</legend>
        <div class="form-field">
            {{ search.dmuploadallowed }}
            <label for="id_dmuploadallowed" class="field-label">Only packages with DM upload allowed enabled</label>
        </div>
        </fieldset>
        <fieldset>
        <legend>Binary search filters</legend>
        <div class="form-field">
            {{ search.essential }}
            <label for="id_essential" class="field-label">Only essential packages</label>
        </div>
        <div class="form-field">
            {{ search.buildessential }}
            <label for="id_buildessential" class="field-label">Only build-essential packages</label>
        </div>
        </fieldset>
    </div> <!-- filters -->

    <h3><a href="#">Output options</a></h3>
    <div> <!-- Output options -->
        <div class="form-field">
            {{ search.homepage }}
            <label for="id_homepage" class="field-label">Show package homepage</label>
        </div>
        <div class="form-field">
            {{ search.popcon }}
            <label for="id_popcon" class="field-label">Show package popularity statistics (binary searches only)</label>
        </div>
        <div class="form-field">
            {{ search.showquery }}
            <label for="id_showquery" class="field-label">Show auto-generated SPARQL query</label>
        </div>
        <div class="form-field">
            {{ search.tojson }}
            <label class="field-label">Return JSON instead of HTML</label>
        </div>
        <div class="form-field">
            <label class="field-label">Order by:</label>
            {{ search.sort }}
        </div>
    </div>

    </div> <!-- accordion -->

    <div class="submit-button">
        <input id="search-submit" type="submit" class="fg-button ui-state-default ui-corner-all" value="Get my results!"/>
    </div>
    </form>
</div>

webapps/django/templates/debian/search/sparql.html
<div id="tab-sparql">
    <div class="ui-widget">
        <div class="ui-state-highlight ui-corner-all" style="font-size: small; margin-top: 20px; padding: 0 .7em;"> 
            <p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
                Looking for examples? Click help tab!</p>
        </div>
    </div>

    <form action="{% url debian.views.sparql %}" method="post">

        <div class="query-textarea">
        <label for="id_ns" class="field-label">Prefixes:</label>
            <span class="field-comment">
                (you won't probably need to modify this)
            </span>
            {{ sparql.ns }}
        </div>
        {% for error in sparql.ns.errors %}
            <div class="ui-widget">
                <div class="ui-state-error ui-corner-all"
                    style="width: 40%; padding: 0 .7em; margin-bottom: .2em;"> 
                <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
                <strong>Error:</strong> {{ error }}</p>
                </div>
            </div>
        {% endfor %}

        <div class="query-textarea">
        <label for="id_query" class="field-label">Query:</label>
            <span class="field-comment">
                (only SELECT queries are allowed. FROM, LIMIT and OFFSET
                statements will be ignored. LIMIT will be set to 100)
            </span>
            {{ sparql.query }}
        </div>
        {% for error in sparql.query.errors %}
            <div class="ui-widget">
                <div class="ui-state-error ui-corner-all"
                    style="width: 40%; padding: 0 .7em; margin-bottom: .2em;"> 
                <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
                <strong>Error:</strong> {{ error }}</p>
                </div>
            </div>
        {% endfor %}

        <div class="form-field">
            {{ sparql.tojson_sparql }}
            <label class="field-label">Return JSON instead of HTML</label>
        </div>
        <div class="submit-button">
            <input id="sparql-submit" type="submit" class="fg-button ui-state-default ui-corner-all" value="Execute Query"/>
        </div>
    </form>
</div>